name: build
on: [push, pull_request]

jobs:
  build:
    uses: charmbracelet/meta/.github/workflows/build.yml@main
    with:
      go-version: ""
      go-version-file: ./go.mod
    secrets:
      gh_pat: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
